# Generated by Django 6.1.1 on 2026-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listinginterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
