# Generated by Django 6.1.1 on 2026-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_studentregistry_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistry',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
