# Generated by Django 6.1.1 on 2026-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_studentregistry_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
